--NO INSERTA NINGUN DATO
BEGIN;
INSERT INTO ventas (total)
VALUES (999);
INSERT OR ROLLBACK INTO ventas (total)
VALUES (-10);
COMMIT;


--INSERTA SOLO EL 999
BEGIN;
INSERT INTO ventas (total)
VALUES (999);
INSERT OR ROLLBACK INTO ventas (total)
VALUES (-10);
COMMIT;
ROLLBACK;