-- 	FAIL

--	ABORT
CREATE TABLE "ventas2"(
"id"	INTEGER PRIMARY KEY ON CONFLICT ABORT, 
"id_vendedor" INTEGER,
"total" REAL CHECK ("total">=0),
"fecha" TEXT);

--NO INSERTA NINGUN DATO PORQUE EL ABORT VUELVE ATRAS TODA LA TRANSACCION ANTE UN ERROR (REPITE ID 1)
INSERT INTO ventas2 (id, total) 
VALUES (1,200),
(2,200), 
(3,300),
(1,400),
(4,500);